language: elixir

otp_release:
  - 18.0
  - 19.3
  - 20.0
  - 21.0

elixir:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8

matrix:
  exclude:
    - otp_release: 18.0
      elixir: 1.6
    - otp_release: 20.0
      elixir: 1.2
    - otp_release: 20.0
      elixir: 1.3
    - otp_release: 21.0
      elixir: 1.2
    - otp_release: 21.0
      elixir: 1.3
    - otp_release: 21.0
      elixir: 1.4
    - otp_release: 21.0
      elixir: 1.5
    - otp_release: 18.0
      elixir: 1.8
    - otp_release: 19.3
      elixir: 1.8

script:
  - mix local.hex --force
  - mix deps.get
  - mix ci_tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0cb4f1057969bd327ed8
    on_success: change
    on_failure: always
    on_start: false
